#INNER JOIN
SELECT #COLUMNS FROM #TABLE_A INNER JOIN #TABLE_B ON #COLUMNS FOR JOINT  ;

#RIGHT JOIN
SELECT #COLUMNS FROM #TABLE_A RIGHT JOIN #TABLE_B ON #COLUMNS FOR JOINT ;

#LEFT JOIN
SELECT #COLUMNS FROM #TABLE_A LEFT JOIN #TABLE_B ON #COLUMNS FOR JOINT ;

#[NOT]EXIST
SELECT #COLUMNS FROM #TABLE WHERE #COLUMS [NOT]EXIST(SELECT #COLUMNS FROM #TABLE WHERE #CONDITION;)

#[NOT]IN
SELECT #COLUMNS FROM #TABLE WHERE #COLUMS [NOT]IN(SELECT #COLUMNS FROM #TABLE WHERE #CONDITION;)

#UNION
SELECT #COLUMNS FROM #TABLE_A UNION SELECT #COLUMNS FROM #TABLE_B ORDER BY #ORDER CONDITION;

