#SELECT
SELECT #COLUMNS FROM #TABLE;

#WHERE
SELECT #COLUMNS FROM #TABLE WHERE #CONDITION;

#LIKE
SELECT #COLUMNS FROM #TABLE WHERE #COLUMN LIKE #CONDITION ;

#Comparison0perator
#= : equal
#<> : not equal
#> : more
#< : less
#>= :more or equal
#<= :less or equal
#[NOT]LIKE() : containing patterns in()(or not contain)
#IS [NOT]NULL : null(or not null)
#[NOT]IN（） :　Containing somthing of in()
＃BETWEEN A AND B:  

#ORDER BY ASC
SELECT #COLUMNS FROM #TABLE ORDER BY #KEYCOLUMNS ASC;
#ORDER BY DESC
SELECT #COLUMNS FROM #TABLE ORDER BY #KEYCOLUMNS DESC;

#GROUP BY
SELECT #COLUMNS FROM #TABLE GROUP BY #KEYCOLUMNS ;

#HAVING
SELECT #COLUMNS FROM #TABLE GROUP BY #KEYCOLUMNS HAVING #CONDITION;

#AS
SELECT #COLUMNS AS #NEWNAME FROM #TABLE GROUP BY #KEYCOLUMNS HAVING #CONDITION;

#CASE 
SELECT #COLUMN CASE WHEN #CONDITION ~ FROM #TABLE;